------------------------------------
--------------SCN_OPDB--------------
------------------------------------

CREATE SCHEMA IF NOT EXISTS SCN_OPDB;

SET SCHEMA SCN_OPDB;

--
-- EXTERNAL_SYSTEM_RETRY_LOG  (Table)
--

CREATE TABLE IF NOT EXISTS SCN_OPDB.EXTERNAL_SYSTEM_RETRY_LOG
(
  RETRY_ID      NUMBER          AUTO_INCREMENT,
  STATUS        VARCHAR2(30)    NOT NULL,
  RETRY_COUNT   NUMBER(3)       NOT NULL,
  KEY           VARCHAR2(50),
  TOPIC         VARCHAR2(50),
  TOPIC_EVENT   VARCHAR2(50),
  ENDPOINT_URL  VARCHAR2(256),
  PAYLOAD       CLOB,
  HTTP_HEADERS  VARCHAR2(256),
  HTTP_METHODS  VARCHAR2(256),
  CREATED_DT    DATE            NOT NULL,
  CREATED_BY    VARCHAR2(100)   NOT NULL,
  MODIFIED_DT   DATE,
  MODIFIED_BY   VARCHAR2(100)
);
