package net.securustech.ews.service.types;

import lombok.Getter;
import net.securustech.ews.logger.ExternalSystem;

import java.util.stream.Stream;

@Getter
public enum ExternalOperation {

//    ###Billing Service - BO###
    BO_CREATE_CUSTOMER("BO_CREATE_CUSTOMER"),
    BO_UPDATE_CUSTOMER("BO_UPDATE_CUSTOMER"),
    BO_GET_VISITOR_DETAIL("BO_GET_VISITOR_DETAIL"),
    BO_ADD_SITE("BO_ADD_SITE"),
    BO_UPDATE_VIDEO_CALL("BO_UPDATE_VIDEO_CALL"),

//    ###SVV Service - SVV###
    SVV_ADD_SITE("SVV_ADD_SITE"),
    SVV_GET_VISITOR_DETAIL("SVV_GET_VISITOR_DETAIL"),
    SVV_GET_VISITOR_SITES("SVV_GET_VISITOR_SITES"),
    SVV_GET_VISITOR_TYPES("SVV_GET_VISITOR_TYPES"),
    SVV_UPDATE_VISITOR("SVV_UPDATE_VISITOR"),
    SVV_GET_PUBLIC_LOCATION("SVV_GET_PUBLIC_LOCATION"),
    SVV_SEARCH_USERS("SVV_SEARCH_USERS"),
    SVV_GET_CONFIG("SVV_GET_CONFIG"),
    SVV_GET_SITE("SVV_GET_SITE"),
    SVV_GET_RELATIONSHIP_OPTIONS("SVV_GET_RELATIONSHIP_OPTIONS"),
    SVV_SAVE_APPOINTMENT("SVV_SAVE_APPOINTMENT"),
    SVV_UPDATE_APPOINTMENT_STATUS("SVV_UPDATE_APPOINTMENT_STATUS"),
    SVV_CANCEL_APPOINTMENT("SVV_CANCEL_APPOINTMENT"),
    SVV_UPDATE_DATE_TIME("SVV_UPDATE_DATE_TIME"),
    SVV_GET_TERMS_AND_CONDITIONS("SVV_GET_TERMS_AND_CONDITIONS"),
    SVV_REQUEST_INMATE_ACCESS("SVV_REQUEST_INMATE_ACCESS"),
    SVV_GET_ALLOW_BLOCK_LIST("SVV_GET_ALLOW_BLOCK_LIST"),

//    ###EMS Service - EMS###
    EMS_SEND_NOTIFICATION("EMS_SEND_NOTIFICATION"),

//    ###Scheduler Service - SCHEDULER###
    SCHEDULER_CANCEL_VISITS("SCHEDULER_CANCEL_VISITS"),
    SCHEDULER_MOVE_CANCEL_VISITS("SCHEDULER_MOVE_CANCEL_VISITS"),
    SCHEDULER_CREATE_APPOINTMENT("SCHEDULER_CREATE_APPOINTMENT"),
    SCHEDULER_UPDATE_APPOINTMENT("SCHEDULER_UPDATE_APPOINTMENT"),
    SCHEDULER_CANCEL_ALL("SCHEDULER_CANCEL_ALL"),
    SCHEDULER_RESCHEDULE("SCHEDULER_RESCHEDULE"),
    SCHEDULER_UPDATE_INFO("SCHEDULER_UPDATE_INFO"),
    SCHEDULER_MOVE_TERMINAL("SCHEDULER_MOVE_TERMINAL"),
    SCHEDULER_GET_IMPACTED_VISITS("SCHEDULER_GET_IMPACTED_VISITS"),

//    ###EWS Service - EWS###
    EWS_CUSTOMERS_GET_PRODUCTS("EWS_CUSTOMERS_GET_PRODUCTS"),
    EWS_CUSTOMERS_GET_RELATIONSHIPS("EWS_CUSTOMERS_GET_RELATIONSHIPS"),

    //MConnStore  - MCONNSTORE###
    MCONNSTORE_GET_PRE_RECORD_NAME("MCONNSTORE_GET_PRE_RECORD_NAME"),
    MCONNSTORE_DELETE_PRE_RECORD_NAME("MCONNSTORE_DELETE_PRE_RECORD_NAME"),


    UNKNOWN("UNKNOWN");

    private String operationType;

    ExternalOperation(String operationType) {
        this.operationType = operationType;
    }

    public ExternalSystem getExternalSystem() {
        return Stream.of(ExternalSystem.values()).filter(d -> operationType.startsWith(d.name())).findFirst().get();
    }
}
